import type { Metadata } from "next";
import {
	Big_Shoulders_Stencil_Text,
	Big_Shoulders_Text,
	Antonio,
} from "next/font/google";
import "./globals.css";
import Header from "@/layout/Header/Header";

const bsst = Big_Shoulders_Stencil_Text({
	subsets: ["latin"],
	variable: "--bsst",
});

const bst = Big_Shoulders_Text({
	subsets: ["latin"],
	variable: "--bst",
});

const antonio = Antonio({
	subsets: ["latin"],
	variable: "--antonio",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={[bsst.variable, bst.variable, antonio.variable].join(" ")}
			>
				<Header />
				{children}
			</body>
		</html>
	);
}
