import type { Metadata } from "next";
import {
	Big_Shoulders_Stencil_Text,
	Big_Shoulders_Text,
	Antonio,
} from "next/font/google";
import "./globals.css";

const bsst = Big_Shoulders_Stencil_Text({ subsets: ["latin"] });
const bst = Big_Shoulders_Text({ subsets: ["latin"] });
const antonio = Antonio({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={[bsst.className, bst.className, antonio.className].join(" ")}
			>
				{children}
			</body>
		</html>
	);
}
